### ISSUE TITLE
participitant added and left notifications are missing

### ISSUE THREAD

**Issue by asadumair** [DolbyIO/comms-sdk-react-native#87] opened 2023-03-13 11:04 UTC
When we add a new listener how we can check or know the new user is came?? so please tell me the way because these two type of notifications are not available in react native if these are available then we can identify using these notifications

**Comment by graduad** [comment] 2023-03-13 11:35
Seems to be a duplicate of https://github.com/DolbyIO/comms-sdk-react-native/issues/75 and https://github.com/DolbyIO/comms-sdk-react-native/issues/82. 

In the mean time participant events can be listened to from the conference service. There we have `ParticipantAdded` and `ParticipantUpdated`. If the later occurs, the status of the participant can be checked. If it is LEFT, it means that the participant has left the conference.

**Closed by graduad** 2023-03-13 11:35 UTC
Labels: duplicate

**Comment by asadumair** [comment] 2023-03-14 11:45
for listner this is not working
