### ISSUE TITLE
Some streams have blank IDs

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#154] opened 2023-05-23 09:32 UTC
Some Stream Removed events have a blank ID which means we don't know which Stream to remove from the app.

**Comment by graduad** [comment] 2023-05-23 09:34
Streams without stream ids have been observed during logging of responses from the native iOS and Android SDKs. Please see logs below.

iOS: 

```
2023-04-21 18:24:52.937 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 0b9431e3-8b0f-3733-a28a-3dd851ecae56, label: ec94a6f3-c28e-003b-6f54-000000000000, videoStream: 1, type: Camera
2023-04-21 18:24:59.565 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 0b9431e3-8b0f-3733-a28a-3dd851ecae56, label: ec94a6f3-c28e-003b-6f54-000000000000, videoStream: 0, type: Camera
2023-04-21 18:25:10.768 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 59dbdb20-d421-32e2-a828-bfe4b91e5ea1, label: 0_camera_59dbdb20-d421-32e2-a828-bfe4b91e5ea1, videoStream: 0, type: Camera
2023-04-21 18:25:11.627 28500-28500 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 59dbdb20-d421-32e2-a828-bfe4b91e5ea1, label: 0_camera_59dbdb20-d421-32e2-a828-bfe4b91e5ea1, videoStream: 1, type: Camera
2023-04-21 18:25:32.435 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 59dbdb20-d421-32e2-a828-bfe4b91e5ea1, label: 0_camera_59dbdb20-d421-32e2-a828-bfe4b91e5ea1, videoStream: 0, type: Camera
2023-04-21 18:25:32.439 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 59dbdb20-d421-32e2-a828-bfe4b91e5ea1, label: , videoStream: 0, type: Camera
2023-04-21 18:25:32.596 28500-28500 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 59dbdb20-d421-32e2-a828-bfe4b91e5ea1, label: , videoStream: 0, type: Camera
```

Android:

```
2023-04-21 18:27:36.145 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 0b9431e3-8b0f-3733-a28a-3dd851ecae56, label: ec94a6f3-c28e-003b-6f54-000000000000, videoStream: 1, type: Camera
2023-04-21 18:27:45.524 28500-29551 [STREAM]                com.example.reactnativedolbyiosdk    D  on update: peerId: 0b9431e3-8b0f-3733-a28a-3dd851ecae56, label: ec94a6f3-c28e-003b-6f54-000000000000, videoStream: 0, type: Camera
```

**Comment by graduad** [comment] 2023-05-26 14:02
@kbetl-dlb I remember that we had logs from Android for this. If you find them please attach them to this issue.

**Comment by kbetl-dlb** [comment] 2023-06-09 11:03
* STOP audio on IOS and collect logs on android
2023-06-09 12:51:22.139 20545-20545 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamRemovedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: , video: [], audio: [] }


 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": ""
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [],
    "audioTransmitting": false,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}


* START/STOP video on IOS and collects logs on ANDROID

2023-06-09 12:54:25.680 20545-20545 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: 0_camera_66afd98f-09c3-320f-b1d1-62409cb22557, video: [com.voxeet.android.media.stream.VideoTrack@37b3d9c], audio: [null] }

 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}

* After stop video three stream update appear and label (id) are missing

2023-06-09 12:55:18.831 20545-24380 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: 0_camera_66afd98f-09c3-320f-b1d1-62409cb22557, video: [], audio: [null] }
2023-06-09 12:55:18.836 20545-24380 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: , video: [], audio: [null] }
2023-06-09 12:55:18.972 20545-20545 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: , video: [], audio: [null] }

 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}
 LOG  attach
 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": ""
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": ""
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}
 LOG  attach
 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": ""
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": ""
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}

**Comment by kbetl-dlb** [comment] 2023-06-09 11:08
* START/STOP video on IOS and collects logs on ANDROID

```
2023-06-09 12:54:25.680 20545-20545 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: 0_camera_66afd98f-09c3-320f-b1d1-62409cb22557, video: [com.voxeet.android.media.stream.VideoTrack@37b3d9c], audio: [null] }

 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}
```

* After stop video three stream update appear and label (id) are missing

```
2023-06-09 12:55:18.831 20545-24380 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: 0_camera_66afd98f-09c3-320f-b1d1-62409cb22557, video: [], audio: [null] }
2023-06-09 12:55:18.836 20545-24380 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: , video: [], audio: [null] }
2023-06-09 12:55:18.972 20545-20545 [STREAM]                com.example.reactnativedolbyiosdk    D  onStreamUpdatedEvent: participant:  Participant{id='66afd98f-09c3-320f-b1d1-62409cb22557', participantInfo=ParticipantInfo{name='Belle Clarke', externalId='', avatarUrl='null'}, status=ON_AIR, quality='null'}, streams: { label: , video: [], audio: [null] }

 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": "0_camera_66afd98f-09c3-320f-b1d1-62409cb22557"
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}
 LOG  attach
 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": ""
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": ""
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}
 LOG  attach
 LOG  STREAMS CHANGE EVENT DATA:
 {
  "stream": {
    "videoTracks": [],
    "audioTracks": [],
    "type": "CAMERA",
    "id": ""
  },
  "participant": {
    "type": "USER",
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [
      {
        "videoTracks": [],
        "audioTracks": [],
        "type": "CAMERA",
        "id": ""
      }
    ],
    "audioTransmitting": true,
    "info": {
      "externalId": "",
      "name": "Belle Clarke"
    }
  }
}
```

**Comment by mateuszglapiak-dolby** [comment] 2023-06-09 11:24
iOS - Start Audio
`{
  "participant": {
    "type": "USER",
    "audioReceivingFrom": false,
    "audioTransmitting": true,
    "streams": [
      {
        "type": "CAMERA",
        "id": "",
        "videoTracks": [],
        "audioTracks": [
          "00000000-0000-0000-0000-000000000000_audio"
        ]
      }
    ],
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "info": {
      "avatarUrl": null,
      "name": "Belle Clarke",
      "externalId": ""
    }
  },
  "stream": {
    "audioTracks": [
      "00000000-0000-0000-0000-000000000000_audio"
    ],
    "type": "CAMERA",
    "id": "",
    "videoTracks": []
  }
}`

**Comment by mateuszglapiak-dolby** [comment] 2023-06-09 11:24
iOS - Stop Audio
```
{
  "participant": {
    "info": {
      "externalId": "",
      "name": "Belle Clarke",
      "avatarUrl": null
    },
    "type": "USER",
    "audioReceivingFrom": false,
    "id": "66afd98f-09c3-320f-b1d1-62409cb22557",
    "status": "CONNECTED",
    "streams": [],
    "audioTransmitting": false
  },
  "stream": {
    "videoTracks": [],
    "type": "CAMERA",
    "id": "",
    "audioTracks": [
      "00000000-0000-0000-0000-000000000000_audio"
    ]
  }
}
```

**Comment by mateuszglapiak-dolby** [comment] 2023-06-13 11:06
To reproduce blank id on iOS:
1. remove all streams (turn off audio and video) on iOS device
2. add an audio stream
3. most of the time you will get a blank id

**Comment by rkanu-dolby** [comment] 2023-06-13 17:05
I confirm that on Android the problem is in SDK itself.
We are working on it.

**Comment by graduad** [comment] 2023-07-24 08:44
@rkanu-dolby any updates related to this issue?

**Comment by rkanu-dolby** [comment] 2023-07-24 08:46
Hi. For Android it is fixed in SDK 3.10.0

**Comment by graduad** [comment] 2023-07-24 09:16
Testing in React Native is needed.

**Comment by mpozy** [comment] 2023-08-09 08:44
Tested. Works properly.

**Closed** 2023-08-21 09:20 UTC
Labels: Maybe native
